###--------------------------------
### PARTIE 1 : Création des comptes
###--------------------------------
### 1/ Créer l'admin
POST http://localhost:3000/users
Content-Type: application/json

{
    "login": "AdminChef",
    "email": "admin@test.com",
    "password": "adminpass",
    "role": "ADMIN"
}

### 2/ Créer un UTILISATEUR STANDARD
POST http://localhost:3000/users
Content-Type: application/json

{
    "login": "Utilisateur",
    "email": "user@test.com",
    "password": "userpass",
    "role": "USER"
}

### 3/ Créer un DEUXIÈME UTILISATEUR
POST http://localhost:3000/users
Content-Type: application/json

{
    "login": "Voleur",
    "email": "voleur@test.com",
    "password": "badpass",
    "role": "USER"
}


###------------------------------------------------
### PARTIE 2 : Connexion et récupération des tokens
###------------------------------------------------

### 1/ Connexion admin
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "adminpass"
}

### 2/ Connexion UTILISATEUR NORMAL

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "userpass"
}

### 3/ Connexion VOLEUR

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "voleur@test.com",
    "password": "badpass"
}


###----------------
### Zone des Tokens
###----------------
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjUzOTg3NjAsImV4cCI6MTc2NTQwMjM2MH0.nFvl5fmcNmtHC-LzzrVnkJ4mHttRYCBkuu5SCFlkR1g
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2NTM5ODc4MSwiZXhwIjoxNzY1NDAyMzgxfQ.gg_aUkrgb4kmGSj0STfwt6z1fBichgmw3mVLQDEAdno
@voleurToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2NTM5ODc5MywiZXhwIjoxNzY1NDAyMzkzfQ.uX5xt13E9OJVyFKqSwiiYOkHQboeFJN956NnCWXN1eE


###----------------------------------------------------------------
### PARTIE 3 : FONCTIONNALITÉS "SHOPPING LIST" (Utilisateur Normal)
###----------------------------------------------------------------

### 1/ Créer une liste de courses (En tant qu'utilisateur normal)
POST http://localhost:3000/shopping-lists
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "title": "Ingrédients pour la tartiflette",
    "status": "OPEN"
}

### 2/ Voir mes listes (Doit afficher la liste "Pizza")
GET http://localhost:3000/shopping-lists
Authorization: Bearer {{userToken}}

### 3/ Modifier la liste
# Remplacez '1' par l'ID réel de la liste si besoin
PATCH http://localhost:3000/shopping-lists/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "status": "COMPLETED",
    "title": "Pizza Party (Fini)"
}

### 4/ Supprimer la liste
DELETE http://localhost:3000/shopping-lists/1
Authorization: Bearer {{userToken}}

###-----------------------------
### PARTIE 4 : Tests de sécurité
###-----------------------------

### 1/ Le Voleur essaie de voir les listes de l'Utilisateur Normal
#Attendu : 200 OK mais un tableau VIDE []
GET http://localhost:3000/shopping-lists
Authorization: Bearer {{voleurToken}}

### 2/ Le Voleur essaie de modifier la liste n°1 qui ne lui appartient pas
#Attendu : 403 Forbidden ou 404 Not Found
PATCH http://localhost:3000/shopping-lists/5
Content-Type: application/json
Authorization: Bearer {{voleurToken}}

{
    "title": "J'ai piraté ta liste"
}

###-------------------------------------------------------
### PARTIE 5 : ADMINISTRATION utilisateur admin uniquement
###-------------------------------------------------------

### 1/ Voir tous les utilisateurs inscrits
GET http://localhost:3000/users
Authorization: Bearer {{adminToken}}

### 1/ Admin qui voit toutes les listes de courses de tout le monde
GET http://localhost:3000/shopping-lists
Authorization: Bearer {{adminToken}}