###--------------------------------
### PARTIE 1 : Création des comptes
###--------------------------------
### 1/ Créer l'admin
POST http://localhost:3000/users
Content-Type: application/json

{
    "login": "AAdminChef",
    "email": "Aadmin@test.com",
    "password": "adminpass",
    "role": "ADMIN"
}

### 2/ Créer un UTILISATEUR STANDARD
POST http://localhost:3000/users
Content-Type: application/json

{
    "login": "Utilisateur",
    "email": "user@test.com",
    "password": "userpass",
    "role": "USER"
}

### 3/ Créer un DEUXIÈME UTILISATEUR
POST http://localhost:3000/users
Content-Type: application/json

{
    "login": "Voleur",
    "email": "voleur@test.com",
    "password": "badpass",
    "role": "USER"
}


###------------------------------------------------
### PARTIE 2 : Connexion et récupération des tokens
###------------------------------------------------

### 1/ Connexion admin
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "Aadmin@test.com",
    "password": "adminpass"
}

### 2/ Connexion UTILISATEUR NORMAL

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "userpass"
}

### 3/ Connexion VOLEUR

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "voleur@test.com",
    "password": "badpass"
}


###----------------
### Zone des Tokens
###----------------
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU0NjI5MjcsImV4cCI6MTc2NTQ2NjUyN30.tENWpKC7Up_x4DLvyCCd9zdJHL0WKz4cL1pOutUlggs
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2NTQ2Mjk0MiwiZXhwIjoxNzY1NDY2NTQyfQ.sZODrMsKeEKlWUXEvM8SUAdaezDuRVeHT1Y5rpm3AQg
@voleurToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2NTQ2Mjk1NCwiZXhwIjoxNzY1NDY2NTU0fQ.XjxLxRhsg52i9jdURh3RKjSat3ncurLPMo4v-kFjwRI


###----------------------------------------------------------------
### PARTIE 3 : FONCTIONNALITÉS "SHOPPING LIST" (Utilisateur Normal)
###----------------------------------------------------------------

### 1/ Créer une liste de courses (En tant qu'utilisateur normal)
POST http://localhost:3000/shopping-lists
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "title": "Ingrédients pour la tartiflette",
    "status": "OPEN"
}

### 2/ Voir mes listes (Doit afficher la liste "Tartiflette")
GET http://localhost:3000/shopping-lists
Authorization: Bearer {{userToken}}

### 3/ Modifier la liste
# Remplacez '1' par l'ID réel de la liste si besoin
PATCH http://localhost:3000/shopping-lists/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "status": "COMPLETED",
    "title": "Pizza Party (Fini)"
}

### 4/ Supprimer la liste
DELETE http://localhost:3000/shopping-lists/1
Authorization: Bearer {{userToken}}

###-----------------------------
### PARTIE 4 : Tests de sécurité
###-----------------------------

### 1/ Le Voleur essaie de voir les listes de l'Utilisateur Normal
#Attendu : 200 OK mais un tableau VIDE []
GET http://localhost:3000/shopping-lists
Authorization: Bearer {{voleurToken}}

### 2/ Le Voleur essaie de modifier la liste n°1 qui ne lui appartient pas
#Attendu : 403 Forbidden ou 404 Not Found
PATCH http://localhost:3000/shopping-lists/2
Content-Type: application/json
Authorization: Bearer {{voleurToken}}

{
    "title": "J'ai piraté ta liste"
}

###-------------------------------------------------------
### PARTIE 5 : Adminnistration utilisateur admin uniquement
###-------------------------------------------------------

### 1/ Voir tous les utilisateurs inscrits
GET http://localhost:3000/users
Authorization: Bearer {{adminToken}}

### 1/ Admin qui voit toutes les listes de courses de tout le monde
GET http://localhost:3000/shopping-lists
Authorization: Bearer {{adminToken}}

### -------------------------------
### PARTIE 6 : Gestion des recettes
### -------------------------------

### 1/ Créer une Recette privée (USER normal)
POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "title": "Pâtes Carbonara Secrètes",
    "description": "La vraie recette italienne sans crème",
    "steps": "1. Guanciale. 2. Pecorino. 3. Oeufs. 4. Poivre.",
    "isPublic": false
}
### Attendu : 201 Created

### 2/ Créer une Recette Publique (USER Normal)
POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "title": "Omelette simple",
    "description": "Pour les débutants",
    "steps": "Casser les oeufs et cuire.",
    "isPublic": true
}
### Attendu : 201 Created

### 3/ Voir toutes les recettes visibles
# L'utilisateur doit voir : Ses 2 recettes (privée et publique)
GET http://localhost:3000/recipes
Authorization: Bearer {{userToken}}
# Attendu : 200 OK -> Tableau avec les 2 recettes

### 4/ Test d'Isolation (Le Voleur regarde)
# Le Voleur ne doit voir que la recette "Omelette simple".
# Il ne doit pas voir "Pâtes Carbonara".
GET http://localhost:3000/recipes
Authorization: Bearer {{voleurToken}}
# Attendu : 200 OK Tableau avec 1 seule recette

### 5/ Modifier une recette -> L'auteur modifie sa recette
# Remplacez l'ID '1' par l'ID réel de la Carbonara si besoin
PATCH http://localhost:3000/recipes/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "title": "Pâtes Carbonara (Meilleures)"
}
### Attendu : 200 OK

### 6/ Tentative de piratage (Le Voleur essaie de modifier l'Omelette de l'autre)
PATCH http://localhost:3000/recipes/2
Content-Type: application/json
Authorization: Bearer {{voleurToken}}

{
    "description": "J'ai ruiné ta recette"
}
### Attendu : 403 Forbidden (Il n'est pas l'auteur)

### 7/ Suppression Admin
# L'admin n'aime pas les carbonara, il supprime la recette ID 1 ne lui appartenant pas
DELETE http://localhost:3000/recipes/1
Authorization: Bearer {{adminToken}}
# Attendu : 204 No Content (L'admin a tous les droits)